name: HardcoreRevivePlugin
version: '1.0-BETA'
main: net.jakeccz.hrp.HardcoreRevivePlugin
api-version: '1.21'
authors: [ JakeCCz ]
description: Enhances the Hardcore Mode Multiplayer Experience by dropping a dead player's Skull Head that may be Used to Revive The Player!
